
function populateLeaderboard () {
	var shotAllTime = [{"endDate":"01-05-2020"},{"name":"Alejandro Londoño Marín","score":1279},{"name":"Matheus Buonani de la Silva","score":1244},{"name":"Rodrigo Guirger","score":1063},{"name":"Christian Bebel II","score":983},{"name":"Hector Ruiz","score":956},{"name":"Inmundo Frank","score":865},{"name":"Carlo Sabatino Errichiello","score":845},{"name":"Devin Barcenas","score":727},{"name":"Abusaif Talal","score":700},{"name":"Leonardo Anastácio","score":662},{"name":"Edwin Artajo","score":612},{"name":"Davide Vanzan","score":506},{"name":"Levente Göröcs","score":416},{"name":"Josh Vickers","score":382},{"name":"Kale Alexander","score":352},{"name":"Raven Suou","score":342},{"name":"Nathaniel Schroeder","score":310},{"name":"James Smith","score":298},{"name":"Gabe Baer","score":290},{"name":"Nay Poe","score":286}]
	var notShotAllTime = [{"endDate":"01-05-2020"},{"name":"Matheus Buonani de la Silva","score":794},{"name":"Alejandro Londoño Marín","score":675},{"name":"Christian Bebel II","score":530},{"name":"Carlo Sabatino Errichiello","score":498},{"name":"Rodrigo Guirger","score":426},{"name":"Devin Barcenas","score":410},{"name":"Abusaif Talal","score":404},{"name":"Nay Poe","score":396},{"name":"Kale Alexander","score":373},{"name":"Edwin Artajo","score":307},{"name":"Conor Gorman","score":287},{"name":"Hector Ruiz","score":283},{"name":"Inmundo Frank","score":258},{"name":"Davide Vanzan","score":257},{"name":"Harry Lovell","score":247},{"name":"Josh Vickers","score":247},{"name":"Nathaniel Schroeder","score":247},{"name":"Lillian Hu","score":224},{"name":"Marcos Eduardo Bubna","score":220},{"name":"Leonardo Anastácio","score":219}]
	var shotThisWeek = [{"startDate":"","endDate":"03-05-2020"},{"name":"Rodrigo Guirger","score":643},{"name":"Inmundo Frank","score":633},{"name":"Hector Ruiz","score":457},{"name":"Matheus Buonani de la Silva","score":434},{"name":"Christian Bebel II","score":387},{"name":"Devin Barcenas","score":372},{"name":"Carlo Sabatino Errichiello","score":367},{"name":"Alejandro Londoño Marín","score":274},{"name":"Leonardo Anastácio","score":238},{"name":"Abad García","score":156},{"name":"James Barnes","score":123},{"name":"Davide Vanzan","score":89},{"name":"Ryan Ellis Freeman","score":57},{"name":"Josh Vickers","score":51},{"name":"Lila Wille","score":43},{"name":"King Tkw","score":41},{"name":"Victoria Herrera","score":27},{"name":"Hernani Roy Roxas","score":14},{"name":"Robson Lima Junior","score":7},{"name":"Matthew Lemgthy","score":6}]
	var notShotThisWeek = [{"startDate":"","endDate":"03-05-2020"},{"name":"Rodrigo Guirger","score":215},{"name":"Inmundo Frank","score":135},{"name":"Carlo Sabatino Errichiello","score":123},{"name":"Devin Barcenas","score":119},{"name":"Christian Bebel II","score":110},{"name":"Matheus Buonani de la Silva","score":107},{"name":"Hector Ruiz","score":75},{"name":"Leonardo Anastácio","score":68},{"name":"Alejandro Londoño Marín","score":67},{"name":"Abad García","score":43},{"name":"James Barnes","score":25},{"name":"Josh Vickers","score":24},{"name":"Davide Vanzan","score":15},{"name":"Ryan Ellis Freeman","score":15},{"name":"Victoria Herrera","score":12},{"name":"King Tkw","score":12},{"name":"Lila Wille","score":10},{"name":"Matthew Lemgthy","score":5},{"name":"Hernani Roy Roxas","score":5},{"name":"Robson Lima Junior","score":5}]
	var table = document.getElementById("table");
	table.rows[0].cells[0].innerHTML = "<h3><b>Last Week's Leaderboard</b></h3><p>" + shotThisWeek[0].startDate + " - " + shotThisWeek[0].endDate + "</p><br>"
	table.rows[0].cells[1].innerHTML = "<h3><b>All Time Leaderboard</b></h3><p>Updated " + shotThisWeek[0].endDate + "</p><br>"
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[3].innerHTML = "<b>" + shotAllTime[i-1].name + "</b><br><p>Shot " + shotAllTime[i-1].score + " Times</p><br>";
	}
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[4].innerHTML = "<b>" + notShotAllTime[i-1].name + "</b><br><p>Shot " + notShotAllTime[i-1].score + " Times</p><br>";
	}
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[0].innerHTML = "<b>" + shotThisWeek[i-1].name + "</b><br><p>Shot " + shotThisWeek[i-1].score + " Times</p><br>";
	}
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[1].innerHTML = "<b>" + notShotThisWeek[i-1].name + "</b><br><p>Shot " + notShotThisWeek[i-1].score + " Times</p><br>";
	}
}
