
function populateLeaderboard () {
	var shotAllTime = [{"endDate":"15-08-2019"},{"name":"Abusaif Talal","score":582},{"name":"Matheus Buonani de la Silva","score":405},{"name":"Edwin Artajo","score":388},{"name":"Kale Alexander","score":352},{"name":"Devin Barcenas","score":343},{"name":"Raven Suou","score":342},{"name":"Christian Bebel II","score":312},{"name":"Davide Vanzan","score":273},{"name":"Adam Pants","score":271},{"name":"Alejandro Londoño Marín","score":260},{"name":"Adam  Newland","score":257},{"name":"Marcos Eduardo Bubna","score":247},{"name":"Michael Chopade","score":238},{"name":"Harry Lovell","score":209},{"name":"Nay Poe","score":205},{"name":"Sigfried Bussey","score":204},{"name":"Dominic King","score":176},{"name":"Mattaya Topolnicki","score":174},{"name":"Lila Wille","score":164},{"name":"Tim Jones","score":161}]
	var notShotAllTime = [{"endDate":"15-08-2019"},{"name":"Matheus Buonani de la Silva","score":453},{"name":"Kale Alexander","score":373},{"name":"Abusaif Talal","score":345},{"name":"Christian Bebel II","score":303},{"name":"Nay Poe","score":284},{"name":"Devin Barcenas","score":281},{"name":"Harry Lovell","score":247},{"name":"Alejandro Londoño Marín","score":220},{"name":"Marcos Eduardo Bubna","score":220},{"name":"Adam Pants","score":217},{"name":"Conor Gorman","score":196},{"name":"Mattaya Topolnicki","score":193},{"name":"Raven Suou","score":191},{"name":"Sigfried Bussey","score":191},{"name":"Davide Vanzan","score":188},{"name":"Maury Stickman","score":184},{"name":"Lillian Hu","score":183},{"name":"Tim Jones","score":173},{"name":"Edwin Artajo","score":167},{"name":"Jake Alderson","score":150}]
	var shotThisWeek = [{"startDate":"08-09-2019","endDate":"15-09-2019"},{"name":"Alejandro Londoño Marín","score":39},{"name":"Carlo Sabatino Errichiello","score":39},{"name":"Lucas Blazkowicz","score":31},{"name":"Levente Göröcs","score":25},{"name":"Josh Vickers","score":25},{"name":"James Smith","score":22},{"name":"Nawel Larrosa","score":20},{"name":"Guille Osses","score":20},{"name":"Justin Chiang","score":18},{"name":"Matheus Buonani de la Silva","score":17},{"name":"Christian Bebel II","score":16},{"name":"Liard Stojić","score":14},{"name":"Alan Cabrera","score":12},{"name":"Pedro Quinellato Dutra Vieira","score":12},{"name":"Denis Tsitsey","score":11},{"name":"Tomasz Mayer","score":11},{"name":"Abusaif Talal","score":10},{"name":"Nay Poe","score":9},{"name":"Pancho Saavedra","score":9},{"name":"Casten Jamie Johnson","score":7}]
	var notShotThisWeek = [{"startDate":"08-09-2019","endDate":"15-09-2019"},{"name":"Lucas Blazkowicz","score":33},{"name":"Carlo Sabatino Errichiello","score":31},{"name":"Alejandro Londoño Marín","score":23},{"name":"Matheus Buonani de la Silva","score":23},{"name":"Pedro Quinellato Dutra Vieira","score":23},{"name":"Christian Bebel II","score":22},{"name":"James Smith","score":19},{"name":"Nay Poe","score":18},{"name":"Tomasz Mayer","score":15},{"name":"Guille Osses","score":14},{"name":"Conor Gorman","score":13},{"name":"Justin Chiang","score":13},{"name":"Josh Vickers","score":12},{"name":"Liard Stojić","score":10},{"name":"Alan Cabrera","score":10},{"name":"Pancho Saavedra","score":9},{"name":"Levente Göröcs","score":9},{"name":"Nawel Larrosa","score":9},{"name":"Casten Jamie Johnson","score":8},{"name":"Otávio Quinellato","score":7}]
	var table = document.getElementById("table");
	table.rows[0].cells[0].innerHTML = "<h3><b>Last Week's Leaderboard</b></h3><p>" + shotThisWeek[0].startDate + " - " + shotThisWeek[0].endDate + "</p>"
	table.rows[0].cells[1].innerHTML = "<h3><b>All Time Leaderboard</b></h3><p>Updated " + shotThisWeek[0].endDate + "</p>"
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[3].innerHTML = "<b>" + shotAllTime[i-1].name + "</b><br><p>Shot " + shotAllTime[i-1].score + " Times</p><br>";
	}
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[4].innerHTML = "<b>" + notShotAllTime[i-1].name + "</b><br><p>Shot " + notShotAllTime[i-1].score + " Times</p><br>";
	}
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[0].innerHTML = "<b>" + shotThisWeek[i-1].name + "</b><br><p>Shot " + shotThisWeek[i-1].score + " Times</p><br>";
	}
	for(i = 2; i < table.rows.length; i++) {
		table.rows[i].cells[1].innerHTML = "<b>" + notShotThisWeek[i-1].name + "</b><br><p>Shot " + notShotThisWeek[i-1].score + " Times</p><br>";
	}
}
